// The browser chrome: the fake browser window (address bar, nav buttons) that
// wraps every view. Content pages live inside a sandboxed iframe so the model's
// CSS can never touch the chrome. SERPs and the home page are our own markup.
import { getSettings, type Settings } from './settings';

const esc = (s: string) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

interface Boot { mode: 'home' | 'serp' | 'page' | 'settings'; cached: boolean; q?: string; url?: string; from?: string; ctx?: string; }

function shell(opts: { title: string; address: string; content: string; boot: Boot }): string {
  const bootJson = JSON.stringify(opts.boot).replace(/</g, '\\u003c');
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(opts.title)}</title>
<link rel="stylesheet" href="/public/chrome.css">
</head>
<body>
<header id="chrome">
  <div class="nav">
    <button class="navbtn" id="back" title="Back">‹</button>
    <button class="navbtn" id="fwd" title="Forward">›</button>
    <button class="navbtn" id="reload" title="Reload">⟳</button>
    <button class="navbtn" id="home" title="Home">⌂</button>
  </div>
  <form id="omnibox" autocomplete="off">
    <span class="lock">🔒</span>
    <input id="address" name="q" value="${esc(opts.address)}" placeholder="スレタイ検索 or 5ch URL を入力…" spellcheck="false">
  </form>
  <a class="navbtn gear" href="/settings" title="設定 — モデル & エンドポイント">⚙</a>
  <div class="brand">🍣 fake&#8209;5ch <span class="brand-model" title="every byte generated by this model">${esc(getSettings().model)}</span></div>
</header>
<main id="viewport">
${opts.content}
</main>
<script>window.__BOOT=${bootJson};</script>
<script src="/public/app.js"></script>
</body>
</html>`;
}

interface BoardLink { name: string; url: string; }
interface BoardCategory { cat: string; items: BoardLink[]; }

const BOARDS: BoardCategory[] = [
  { cat: 'ニュース・実況', items: [
    { name: 'ニュース速報',     url: 'https://hayabusa.5ch.net/news/' },
    { name: 'ニュース速報＋',   url: 'https://asahi.5ch.net/newsplus/' },
    { name: 'なんでも実況J',    url: 'https://hayabusa.5ch.net/livejupiter/' },
    { name: 'なんでも実況M',    url: 'https://hayabusa.5ch.net/livemarket1/' },
    { name: 'ニュー速VIP',      url: 'https://viper.5ch.net/news4vip/' },
    { name: '嫌儲',             url: 'https://greta.5ch.net/poverty/' },
    { name: '東アジアnews+',    url: 'https://asahi.5ch.net/news4plus/' },
  ]},
  { cat: '雑談・社会', items: [
    { name: '既婚女性',         url: 'https://mevius.5ch.net/ms/' },
    { name: '鬼女',             url: 'https://egg.5ch.net/wmotenai/' },
    { name: '独身男性',         url: 'https://lavender.5ch.net/mendou/' },
    { name: '生活全般',         url: 'https://rosie.5ch.net/kankon/' },
    { name: '政治',             url: 'https://nozomi.5ch.net/seiji/' },
    { name: '経済',             url: 'https://lavender.5ch.net/eco/' },
  ]},
  { cat: '趣味・カルチャー', items: [
    { name: 'モーニング娘。(羊)', url: 'https://egg.5ch.net/morningcoffee/' },
    { name: 'アニメ',           url: 'https://anago.5ch.net/anime/' },
    { name: 'ゲーム',           url: 'https://krsw.5ch.net/gamerpg/' },
    { name: 'オカルト',         url: 'https://mao.5ch.net/occult/' },
    { name: '料理',             url: 'https://rosie.5ch.net/cook/' },
    { name: '一人暮らし',       url: 'https://rosie.5ch.net/homealone/' },
  ]},
];

export function renderHome(stats: { pages: number; serps: number }): string {
  const groups = BOARDS.map((g) => {
    const items = g.items
      .map((b) => `<a class="bd" href="/view?url=${encodeURIComponent(b.url)}&ctx=${encodeURIComponent(b.name)}">${esc(b.name)}</a>`)
      .join('');
    return `<section class="bgrp"><h3>${esc(g.cat)}</h3><div class="bgrp-items">${items}</div></section>`;
  }).join('');

  const content = `<style>
    .ch5{background:#efefef;color:#000;font-family:"MS PGothic","ヒラギノ角ゴシック",sans-serif;padding:24px 32px;min-height:100%}
    .ch5 .brand5{font-size:46px;font-weight:bold;color:#800;letter-spacing:1px;margin:0 0 6px 0}
    .ch5 .sub5{color:#444;margin:0 0 14px 0;font-size:13px}
    .ch5 .modelpill5{display:inline-block;background:#fff;border:1px solid #c00;color:#c00;padding:3px 10px;font-size:12px;margin-bottom:18px;border-radius:2px}
    .ch5 .modelpill5 code{background:transparent;font-family:Menlo,monospace}
    .ch5 .homebox5{display:flex;align-items:center;background:#fff;border:1px solid #888;padding:6px 10px;max-width:560px;margin-bottom:20px}
    .ch5 .homebox5 span{margin-right:8px;color:#888}
    .ch5 .homebox5 input{flex:1;border:0;outline:0;font-size:14px;background:transparent}
    .ch5 .bgrp{background:#fff;border:1px solid #999;margin:10px 0;padding:8px 12px}
    .ch5 .bgrp h3{margin:2px 0 8px 0;font-size:14px;color:#800;border-bottom:1px dotted #999;padding-bottom:4px}
    .ch5 .bgrp-items{display:flex;flex-wrap:wrap;gap:0 14px;font-size:13px;line-height:1.9}
    .ch5 .bgrp-items a{color:#00f;text-decoration:underline}
    .ch5 .bgrp-items a:visited{color:#551a8b}
    .ch5 .stat5{color:#666;font-size:11px;margin-top:18px;border-top:1px dotted #999;padding-top:8px}
    .ch5 .examples5{font-size:12px;color:#444;margin-bottom:18px}
    .ch5 .examples5 a{color:#00f}
  </style>
  <div class="ch5">
    <h1 class="brand5">5ちゃんねる (fake)</h1>
    <p class="sub5">板はあるが、中身は全部このローカルモデルが「もしあったらこんなスレ立ってる」を想像で書いてる。クリックで生成、SQLiteに保存、無限に枝分かれする。</p>
    <div class="modelpill5">⚡ 動力: <code>${esc(getSettings().model)}</code></div>
    <form id="homebox" class="homebox5" autocomplete="off">
      <span>🔍</span>
      <input id="homeinput" placeholder="スレタイ検索（板またぎ）または 5ch URL を直接入力" spellcheck="false" autofocus>
    </form>
    <div class="examples5">
      たとえば:
      <a href="/search?q=${encodeURIComponent('阪神 なんJ')}">阪神 なんJ</a> ·
      <a href="/search?q=${encodeURIComponent('深夜の質問スレ')}">深夜の質問スレ</a> ·
      <a href="/view?url=${encodeURIComponent('https://hayabusa.5ch.net/livejupiter/')}&ctx=${encodeURIComponent('なんJ')}">hayabusa.5ch.net/livejupiter/</a>
    </div>
    ${groups}
    <div class="stat5">この宇宙には <b>${stats.pages}</b> ページ、<b>${stats.serps}</b> 件のスレタイ検索が積もっている。</div>
  </div>`;
  return shell({ title: '5ちゃんねる (fake) — local world model', address: '', content, boot: { mode: 'home', cached: true } });
}

export function renderSerp(opts: { query: string; cachedHtml?: string }): string {
  const inner = opts.cachedHtml ?? skeletonSerp();
  const content = `<div id="serp-root" class="serp-wrap">${inner}</div>${overlay()}`;
  return shell({
    title: `${opts.query} — LLMnet Search`,
    address: opts.query,
    content,
    boot: { mode: 'serp', cached: !!opts.cachedHtml, q: opts.query },
  });
}

export function renderPage(opts: { fakeUrl: string; from?: string; ctx?: string; cached: boolean }): string {
  const iframe = opts.cached
    ? `<iframe id="page-frame" sandbox="allow-same-origin allow-top-navigation-by-user-activation allow-popups allow-forms" src="/raw?url=${encodeURIComponent(opts.fakeUrl)}"></iframe>`
    : `<iframe id="page-frame" sandbox="allow-same-origin allow-top-navigation-by-user-activation allow-popups allow-forms"></iframe>`;
  const content = `${iframe}${overlay()}`;
  return shell({
    title: opts.fakeUrl,
    address: opts.fakeUrl,
    content,
    boot: { mode: 'page', cached: opts.cached, url: opts.fakeUrl, from: opts.from, ctx: opts.ctx },
  });
}

export function renderErrorBody(message: string, links: string[] = []): string {
  // A styled, in-universe error page that STILL contains working links so the
  // user can keep browsing instead of hitting a dead end.
  const linkHtml = links.map((l) => `<li><a href="/view?url=${encodeURIComponent(l)}" target="_top">${esc(l)}</a></li>`).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    body{font-family:system-ui,sans-serif;background:#fff;color:#202124;display:flex;min-height:100vh;align-items:center;justify-content:center;margin:0}
    .box{max-width:560px;padding:40px;text-align:center}
    h1{font-size:42px;margin:0}.sub{color:#5f6368;margin:12px 0 24px}
    code{background:#f1f3f4;padding:2px 6px;border-radius:4px}
    ul{text-align:left;display:inline-block}
  </style></head><body><div class="box">
    <h1>This page failed to materialize</h1>
    <p class="sub">${esc(message)}</p>
    ${links.length ? `<p>But these places exist:</p><ul>${linkHtml}</ul>` : ''}
  </div></body></html>`;
}

export function renderSettings(
  cur: Settings,
  def: Settings,
  ping: { ok: boolean; detail: string },
): string {
  const presets = [
    { name: 'LM Studio (local)', baseUrl: 'http://127.0.0.1:1234/v1' },
    { name: 'Ollama (local)', baseUrl: 'http://127.0.0.1:11434/v1' },
    { name: 'OpenRouter', baseUrl: 'https://openrouter.ai/api/v1' },
    { name: 'OpenAI', baseUrl: 'https://api.openai.com/v1' },
  ];
  const presetBtns = presets
    .map((p) => `<button type="button" class="preset" data-url="${esc(p.baseUrl)}">${esc(p.name)}</button>`)
    .join('');
  const content = `<div class="settings">
    <h1>Settings</h1>
    <p class="sub">Point this app at any OpenAI-compatible chat endpoint. Defaults to local LM Studio.
      Best results come from the world model it was built for — <code>${esc(def.model)}</code>.</p>

    <div class="status-line ${ping.ok ? 'ok' : 'bad'}" id="conn">${ping.ok ? '● connected' : '● not reachable'} — ${esc(ping.detail)}</div>

    <form id="settings-form">
      <label>Endpoint base URL <span>OpenAI-compatible, ends in <code>/v1</code></span>
        <input name="baseUrl" id="f-baseUrl" value="${esc(cur.baseUrl)}" spellcheck="false" placeholder="http://127.0.0.1:1234/v1">
      </label>
      <div class="presets">${presetBtns}</div>

      <label>Model id
        <input name="model" id="f-model" value="${esc(cur.model)}" spellcheck="false" placeholder="${esc(def.model)}">
      </label>

      <label>API key <span>ignored by local servers; required by hosted providers</span>
        <input name="apiKey" id="f-apiKey" type="password" value="${esc(cur.apiKey)}" spellcheck="false" placeholder="lm-studio">
      </label>

      <label class="check">
        <input type="checkbox" name="thinking" id="f-thinking" ${cur.thinking ? 'checked' : ''}>
        <span>Thinking mode <small>let the world model reason before generating each page — higher fidelity, much slower. Experimental on local hardware (see README).</small></span>
      </label>

      <div class="actions">
        <button type="submit" class="primary">Save</button>
        <button type="button" id="test">Test connection</button>
        <button type="button" id="reset" class="ghost">Reset to defaults</button>
        <span id="saved" class="saved" hidden>Saved ✓</span>
      </div>
    </form>
  </div>
  <script>
    (function(){
      var f=document.getElementById('settings-form');
      var conn=document.getElementById('conn');
      document.querySelectorAll('.preset').forEach(function(b){ b.addEventListener('click',function(){ document.getElementById('f-baseUrl').value=b.dataset.url; }); });
      function payload(){ return { baseUrl:f.baseUrl.value, model:f.model.value, apiKey:f.apiKey.value, thinking:f.thinking.checked }; }
      function setConn(p){ conn.className='status-line '+(p.ok?'ok':'bad'); conn.textContent=(p.ok?'● connected':'● not reachable')+' — '+p.detail; }
      f.addEventListener('submit', async function(e){ e.preventDefault();
        var r=await fetch('/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});
        var j=await r.json(); if(j.ping) setConn(j.ping);
        var s=document.getElementById('saved'); s.hidden=false; setTimeout(function(){s.hidden=true;},2000);
      });
      document.getElementById('test').addEventListener('click', async function(){
        conn.textContent='● testing…'; conn.className='status-line';
        await fetch('/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});
        var r=await fetch('/health'); var j=await r.json(); setConn(j.model);
      });
      document.getElementById('reset').addEventListener('click', function(){
        f.baseUrl.value=${JSON.stringify(def.baseUrl)}; f.model.value=${JSON.stringify(def.model)}; f.apiKey.value=${JSON.stringify(def.apiKey)}; f.thinking.checked=${def.thinking};
      });
    })();
  </script>`;
  return shell({ title: 'Settings — LLMnet', address: '', content, boot: { mode: 'settings', cached: true } });
}

function overlay(): string {
  return `<div id="overlay" hidden>
    <div class="loadcard">
      <div class="spinner"></div>
      <div class="status" id="status">Connecting…</div>
      <div class="bar"><div class="bar-fill" id="bar"></div></div>
      <pre class="source" id="source"></pre>
      <div class="hint">The origin server is generating this page token by token.</div>
    </div>
  </div>`;
}

function skeletonSerp(): string {
  const row = `<div class="sk-result"><div class="sk-line sk-crumb"></div><div class="sk-line sk-title"></div><div class="sk-line"></div><div class="sk-line short"></div></div>`;
  return `<div class="sk-serp">${row.repeat(6)}</div>`;
}
